(* This file was generated by lv6 version v6.107.1. *)
(*  lv6 -ec -node cir1 -o exDocV6.ec exDocV6.lus *)
(* on hani-Inspiron-7347 the 10/11/2022 at 11:17:55 *)

node cir1(a:bool; b:bool; c:bool) 
returns (f:bool);
var
   _split_2:bool;
   _split_1:bool;
let
   f = ((_split_1) or (_split_2));
   _split_1 = ((a) and (b));
   _split_2 = (not (c));
tel
-- end of node exDocV6__cir1
